export const data = [
  {
    id: 1680068997820,
    title: "MAGNA SED ADIPISCING",
    subtitle: "LOREM IPSUM DOLOR AMET NULLAM CONSEQUAT ETIAM FEUGIAT",
    text: "Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at. Phasellus sed ultricies mi non congue ullam corper. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.\n Nunc quis dui scelerisque, scelerisque urna ut, dapibus orci. Sed vitae condimentum lectus, ut imperdiet quam. Maecenas in justo ut nulla aliquam sodales vel at ligula. Sed blandit diam odio, sed fringilla lectus molestie sit amet. Praesent eu tortor viverra lorem mattis pulvinar feugiat in turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce ullamcorper tellus sit amet mattis dignissim. Phasellus ut metus ligula. Curabitur nec leo turpis. Ut gravida purus quis erat pretium, sed pellentesque massa elementum. Fusce vestibulum porta augue, at mattis justo. Integer sed sapien fringilla, dapibus risus id, faucibus ante. Pellentesque mattis nunc sit amet tortor pellentesque, non placerat neque viverra.",
    athor: "Jane doe",
    date: "2023-11-01",
    tag: "GENERAL",
    likeCount: 28,
    commentCount: 128,
  },

  {
    id: 1680069925401,
    title: "ULTRICIES SED MAGNA EUISMOD ENIM VITAE GRAVIDA",
    subtitle: "LOREM IPSUM DOLOR AMET NULLAM CONSEQUAT ETIAM FEUGIAT",
    text: "Fusce ex nunc, molestie in nunc eu, luctus dictum velit. Maecenas convallis sed ipsum non commodo. Aenean eu laoreet lorem. Aliquam id lacus nec ante interdum viverra. Praesent ac venenatis ante, at semper nunc. Ut rhoncus sapien sit amet placerat finibus. Curabitur luctus tincidunt molestie. Aliquam porta augue ut nisi efficitur, id accumsan turpis aliquet. Nam tincidunt, lacus at egestas dignissim, lectus nunc tincidunt eros, ut cursus sapien velit eget felis. Quisque nec enim eu eros tempor molestie. Donec consectetur bibendum dui non fermentum. Praesent in porttitor purus. Nullam eget dapibus odio. Proin fermentum pharetra tellus sed ullamcorper. Praesent non massa nec nisi tempus laoreet eget sed lectus.\n Nullam ut mollis dui. Sed non metus a neque placerat cursus. Curabitur finibus ligula eu lorem condimentum rhoncus. Morbi ultricies consectetur bibendum. Proin metus ipsum, ullamcorper nec libero eu, dapibus cursus felis. Vivamus in arcu lectus. Aliquam erat volutpat. Cras gravida nisi ut turpis rhoncus, sit amet malesuada magna ornare. Phasellus finibus eu risus at molestie. Nunc non fermentum mauris. Fusce ac orci finibus, tempor justo id, tristique risus. Donec eget velit nulla. Fusce in euismod nisi.",
    athor: "Jane doe",
    date: "2023-10-25",
    tag: "GENERAL",
    likeCount: 32,
    commentCount: 5,
  },
  {
    id: 1680070110381,
    title: "EUISMOD ET ACCUMSAN",
    subtitle: "LOREM IPSUM DOLOR AMET NULLAM CONSEQUAT ETIAM FEUGIAT",
    text: "Nulla facilisi. Mauris quam tortor, pulvinar in dictum consequat, malesuada ut urna. Proin in felis nulla. Nulla erat neque, aliquet eget euismod vitae, varius non mauris. Etiam libero neque, laoreet a mollis nec, posuere nec ipsum. Nulla mollis tincidunt mauris, ut consectetur lorem faucibus eget. Pellentesque turpis justo, accumsan vitae mi sit amet, ultrices suscipit diam. Morbi non iaculis felis. In vestibulum rutrum magna. Suspendisse sit amet lacus nisi. Etiam dui odio, gravida eget diam eget, tincidunt rutrum nunc. Mauris aliquam lorem est, in hendrerit nulla commodo id. Quisque et gravida sapien, eu ullamcorper felis. Aliquam ultricies tortor eget nisl placerat mattis. Sed lobortis eleifend nisl, ac tempor metus ullamcorper in.\n Donec in risus nec libero molestie pharetra. Nunc mollis ante sed arcu porta, vel eleifend purus commodo. Proin lacinia sed sapien nec efficitur. Nam erat est, luctus a suscipit sed, pretium vel magna. Ut gravida sollicitudin sodales. Cras at malesuada ligula, non faucibus orci. Phasellus non lorem at nunc porta dictum. Etiam sodales nisi et sem dapibus rhoncus. Aliquam erat volutpat.\n Cras accumsan mi velit, quis imperdiet erat rhoncus sed. Suspendisse id dignissim velit, non cursus mi. Fusce enim tellus, auctor vel pellentesque id, maximus nec augue. Sed malesuada condimentum enim et porta. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus mollis ex in ultricies mollis. In ac tortor vulputate, porta purus in, ornare tellus. Praesent id vestibulum odio. Cras non lorem elit. Praesent orci lacus, laoreet ac sapien vitae, iaculis cursus risus.",
    athor: "Jane doe",
    date: "2023-10-22",
    tag: "General",
    likeCount: 30,
    commentCount: 130,
  },
  {
    id: 1680070638874,
    title: "VITAE SED CONDIMENTUM",
    subtitle: "LOREM IPSUM DOLOR AMET NULLAM CONSEQUAT ETIAM FEUGIAT",
    text: "Cras accumsan mi velit, quis imperdiet erat rhoncus sed. Suspendisse id dignissim velit, non cursus mi. Fusce enim tellus, auctor vel pellentesque id, maximus nec augue. Sed malesuada condimentum enim et porta. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus mollis ex in ultricies mollis. In ac tortor vulputate, porta purus in, ornare tellus. Praesent id vestibulum odio. Cras non lorem elit. Praesent orci lacus, laoreet ac sapien vitae, iaculis cursus risus.\n Etiam laoreet, nisl quis pulvinar varius, dolor nulla faucibus justo, eget dignissim ipsum arcu nec tortor. Integer accumsan ipsum eget est elementum luctus. Aenean fringilla justo vel ante luctus, nec faucibus magna ultrices. Integer volutpat quis neque in ultricies. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent ut dui ultricies libero sollicitudin aliquet suscipit vitae est. Fusce interdum leo non lacinia pretium. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse et tortor vitae eros venenatis dictum. Nullam et eros sit amet tortor dictum pulvinar. Cras vehicula varius arcu vel feugiat. Morbi non ipsum ullamcorper, volutpat turpis non, tincidunt nisl.\n Cras condimentum a odio et blandit. Aliquam ornare nec ex a volutpat. Nunc nec nibh ut enim finibus maximus. Nullam vulputate ac diam varius suscipit. Proin dolor sapien, cursus a ligula ac, facilisis finibus elit. Fusce blandit, turpis sed vulputate finibus, dolor sapien dapibus mauris, in rutrum metus nunc id odio. Sed ut pharetra tellus. Donec sit amet sapien vestibulum, fringilla enim in, imperdiet sapien. Proin eget ligula lobortis, aliquam leo sit amet, cursus metus. Fusce tristique gravida interdum.",
    athor: "Jane doe",
    date: "2023-10-20",
    tag: "General",
    likeCount: 30,
    commentCount: 10,
  },
  {
    id: 1680070645829,
    title: "RUTRUM NEQUE ACCUMSAN",
    subtitle: "LOREM IPSUM DOLOR AMET NULLAM CONSEQUAT ETIAM FEUGIAT",
    text: "Vivamus tristique nulla ex, eget consectetur risus elementum ac. Vestibulum tempus lorem non sem lobortis dictum. In et dolor dignissim, elementum risus condimentum, mattis velit. Maecenas quis molestie odio. Sed cursus orci condimentum tortor euismod, id consectetur justo sollicitudin. Aenean imperdiet suscipit nulla, in sollicitudin lacus eleifend eget. Mauris vel mollis mi. Curabitur vel congue felis. Phasellus consectetur libero eget ex iaculis aliquam at at est. Etiam pretium scelerisque lacus eu elementum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec cursus, nisl commodo lobortis interdum, sapien enim sodales purus, a tincidunt ipsum mi vel urna. \n Aenean dapibus sit amet augue quis facilisis. Proin vel vehicula elit. Quisque in turpis vitae lacus tincidunt sollicitudin. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra lectus non imperdiet ornare. Sed quam nisl, ultrices ac neque id, accumsan aliquet quam. Aliquam mi massa, dictum aliquet feugiat sit amet, volutpat ac mauris. Phasellus mattis nulla sed augue viverra malesuada. Aenean rhoncus nulla a sem euismod aliquet. Praesent et sodales elit, vel ullamcorper libero. Pellentesque vulputate commodo mollis.",
    athor: "Jane doe",
    date: "2023-10-19",
    tag: "General",
    likeCount: 3,
    commentCount: 1,
  },
  {
    id: 1680070835839,
    title: "ODIO CONGUE MATTIS",
    subtitle: "LOREM IPSUM DOLOR AMET NULLAM CONSEQUAT ETIAM FEUGIAT",
    text: "Curabitur vestibulum molestie justo, non interdum tellus congue vel. Nullam ac rhoncus nisi. Suspendisse id nulla vel tortor tempor venenatis. Phasellus vitae elementum ipsum. Suspendisse mattis libero eros, eget dapibus est sollicitudin a. Curabitur finibus massa metus. Suspendisse semper nibh ac mauris cursus tincidunt. Aenean nec semper mi. Sed dui tortor, tincidunt in purus vitae, hendrerit gravida tellus. Aenean at leo sit amet libero aliquam fringilla. Nullam venenatis iaculis nulla ac feugiat. Nam cursus massa justo. \n Nulla eget lectus quis urna consectetur interdum in in felis. Vivamus sollicitudin lacus orci, quis tristique risus sagittis a. Nullam ultricies sem nec urna consequat suscipit. Integer hendrerit luctus vestibulum. In vitae metus ligula. Maecenas facilisis rutrum dictum. Mauris ante nisl, aliquam vitae sem nec, pellentesque tincidunt nisi. Etiam auctor, tellus eget porttitor viverra, nisi quam eleifend ipsum, in condimentum lorem erat ut sem. Ut luctus sed elit nec ultrices. Suspendisse pharetra in magna dictum congue. Pellentesque vestibulum purus ac lectus scelerisque pellentesque. Sed at erat diam. Phasellus vehicula at nunc nec aliquam. Nam accumsan eros sit amet diam finibus, ac vestibulum turpis vestibulum. Phasellus sit amet finibus diam. \n Pellentesque eu nibh pellentesque, egestas lacus in, fermentum urna. Vestibulum vulputate nulla sodales velit imperdiet fermentum et nec nunc. Etiam pulvinar tempor leo, eu sollicitudin tellus pharetra quis. Nulla pellentesque tortor ut efficitur luctus. Aenean tristique rhoncus diam eu pulvinar. Integer porttitor elit ut tortor dictum, pellentesque imperdiet est vulputate. Nunc placerat ultricies enim non congue.",
    athor: "Jane doe",
    date: "2023-10-18",
    tag: "General",
    likeCount: 15,
    commentCount: 20,
  },
  {
    id: 1680071068304,
    title: "ENIM NISL VEROEROS",
    subtitle: "LOREM IPSUM DOLOR AMET NULLAM CONSEQUAT ETIAM FEUGIAT",
    text: "Curabitur et dui risus. Cras lectus mi, interdum ac gravida quis, dignissim in elit. Vestibulum at nisl sed elit sagittis consequat. Donec eu quam et nisi consequat ultrices. Integer enim ipsum, bibendum at varius at, dictum a magna. In non auctor magna. Duis sed arcu efficitur, cursus neque id, cursus nunc. Mauris consectetur, urna eu tincidunt mollis, tellus nunc dapibus diam, semper congue sem ipsum quis neque. Ut rutrum eros eget vestibulum malesuada. Aliquam semper eget ante id suscipit. Integer id tellus mauris. \n Nam sagittis nulla suscipit, posuere velit et, malesuada sapien. Nunc nisl odio, sagittis et ullamcorper vestibulum, lobortis et diam. Fusce auctor sed metus sit amet mollis. Phasellus posuere, risus ut efficitur dictum, mi eros pellentesque enim, sit amet blandit ex mauris at augue. Aliquam mi mi, auctor quis cursus sed, convallis semper felis. Phasellus in suscipit odio. Vestibulum commodo porta vehicula. Proin auctor eros malesuada, vulputate mi eget, accumsan dui. \n Integer tempus risus in nunc pharetra, id convallis turpis tincidunt. Sed vel iaculis risus. Morbi lacinia nunc sit amet eros condimentum rhoncus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Duis eu risus mi. Nullam molestie nibh nisl, quis hendrerit nulla ultricies euismod. Suspendisse sodales malesuada pretium. Duis nec laoreet magna, eu maximus nunc. Morbi facilisis, elit et pulvinar ullamcorper, odio nisl tristique erat, eget euismod velit odio at nunc. Nam ipsum massa, dignissim eget diam quis, mattis feugiat nisi. Morbi sollicitudin tempor sagittis. \n Nullam lobortis risus ut lectus suscipit pretium. Pellentesque sed lorem est. Sed aliquam fermentum congue. Donec vitae blandit urna. Quisque vitae tellus quis risus aliquet consequat. Fusce ipsum mauris, rutrum non nulla eget, placerat pretium sapien. Aliquam tincidunt mauris vitae erat dictum pretium. Sed cursus tempor magna. Etiam magna erat, finibus interdum tincidunt non, vehicula in diam.",
    athor: "Jane doe",
    date: "2023-10-17",
    tag: "General",
    likeCount: 5,
    commentCount: 200,
  },
  {
    id: 1680071253429,
    title: "LOREM IPSUM FERMENTUM UT NISL VITAE",
    subtitle: "LOREM IPSUM DOLOR AMET NULLAM CONSEQUAT ETIAM FEUGIAT",
    text: "",
    athor: "Jane doe",
    date: "2023-10-15",
    tag: "General",
    likeCount: 430,
    commentCount: 6540,
  },
  {
    id: 1680071247286,
    title: "CONVALLIS MAXIMUS NISL MATTIS NUNC ID LOREM",
    subtitle: "LOREM IPSUM DOLOR AMET NULLAM CONSEQUAT ETIAM FEUGIAT",
    text: "",
    athor: "Jane doe",
    date: "2023-10-02",
    tag: "General",
    likeCount: 30,
    commentCount: 20,
  },
  {
    id: 1680071241362,
    title: "EUISMOD AMET PLACERAT VIVAMUS PORTTITOR",
    subtitle: "LOREM IPSUM DOLOR AMET NULLAM CONSEQUAT ETIAM FEUGIAT",
    text: "",
    athor: "Jane doe",
    date: "2023-09-25",
    tag: "General",
    likeCount: 18,
    commentCount: 20,
  },
  {
    id: 1680071236122,
    title: "MAGNA ENIM ACCUMSAN TORTOR CURSUS ULTRICIES",
    subtitle: "LOREM IPSUM DOLOR AMET NULLAM CONSEQUAT ETIAM FEUGIAT",
    text: "",
    athor: "Jane doe",
    date: "2023-09-19",
    tag: "General",
    likeCount: 40,
    commentCount: 30,
  },
  {
    id: 1680071229228,
    title: "CONGUE ULLAM CORPER LOREM IPSUM DOLOR",
    subtitle: "LOREM IPSUM DOLOR AMET NULLAM CONSEQUAT ETIAM FEUGIAT",
    text: "",
    athor: "Jane doe",
    date: "2023-09-18",
    tag: "General",
    likeCount: 543,
    commentCount: 3450,
  },
];
